Data Entry PR2
We-Equals-Awesome/Corporators_Frontend pull request #5
Opened 2021-04-06 11:26 UTC by Bhoomika73

There are multiple bugs and problems that have to be still worked upon. 
If the user has not entered the details in one of the steppers and tries to go to the next stepper, the application allows him to go the next stepper.
When the user is trying to enter the details the interface does not appear the way it is expected to.
Media Query has not been used yet.
Few of the icons as per the design haven't been used yet. The required icons will be updated soon.
All necessary modifications will be done by the next PR.

2021-04-15 08:31 UTC, Srikanth-Kandarp requested changes

2021-04-15 08:31 UTC, Srikanth-Kandarp commented on lib/UI/DataEntry.dart
> +import 'package:cropapp/Utils/Icons.dart';
Update the changes and push it by Friday

2021-04-16 16:14 UTC, Apoorva10100 commented
### **Changes to be made**

**1.**  **The text editing controller**
There is a common text editing controller for all the text fields. So, when the value of one field changes, the value of all the fields change, so the same value will be stored throughout.

![image](https://user-images.githubusercontent.com/47321161/115051034-ff2b3880-9ef9-11eb-83a0-264e0c8f2abf.png)

**2.** **The validator**
The height of the text form fields change when the fields are submitted on empty.

![image](https://user-images.githubusercontent.com/47321161/115051466-7a8cea00-9efa-11eb-9e5b-03f065808b96.png)


**3.** **Add a new family member**
Initially there should be no members. When a new member is added, then a new icon must be created. On clicking on the '+' button, it should go to a new form where the details are to be entered again. A new design needs to be made for that (check in with me by tomorrow afternoon)

Also there's too much gap between the buttons of the last stepper and the add family member thing so look into that.
![image](https://user-images.githubusercontent.com/47321161/115053261-91ccd700-9efc-11eb-853d-d51b6680919c.png)

Make the changes by tomorrow so that we can continue with blocs soon

2021-05-22 04:38 UTC, Apoorva10100 commented
1. Rename the pages based on the figma file
2. Comment your code
3. When the details of the head of the family is being taken, do not give any option to input the relationship.

2021-05-28 05:25 UTC, merged